apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apo-dataplane.name" . }}
  labels:
    {{- include "apo-dataplane.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "apo-dataplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/apo-dataplane-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "apo-dataplane.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: check-clickhouse-ready
          image: "{{ tpl .Values.initImage.repository . }}:{{ tpl .Values.initImage.tag . }}"
          imagePullPolicy: {{ tpl .Values.initImage.pullPolicy . }}
          env:
            - name: CLICKHOUSE_URL
              value: {{ .Values.global.clickhouse.host }}:{{ .Values.global.clickhouse.nativePort }}
          command:
            - sh
            - -c
            - |
              CLICKHOUSE_HOST=$(echo $CLICKHOUSE_URL | cut -d ':' -f 1)
              CLICKHOUSE_PORT=$(echo $CLICKHOUSE_URL | cut -d ':' -f 2)
              echo "等待 ${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT} clickhouse启动..."
              while ! nc -z ${CLICKHOUSE_HOST} ${CLICKHOUSE_PORT}; do
                echo "INFO: ClickHouse 连接失败。 将在5s后重新检查"
                sleep 5
              done
              echo "INFO: ClickHouse 连接测试通过"
      containers:
        - image: "{{tpl .Values.image.repository . }}:{{tpl .Values.image.tag . }}"
          imagePullPolicy: {{tpl .Values.image.imagePullPolicy . }}
          name: {{ include "apo-dataplane.name" .}}
          ports:
            - containerPort: 8089
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/dataplane.yml
              name: {{ include "apo-dataplane.name" . }}-config
              subPath: dataplane.yml
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "apo-dataplane.name" . }}-config
          name: {{ include "apo-dataplane.name" . }}-config
        - name: apm-adapter-config
          configMap:
            name: apo-apm-adapter-config