apiVersion: v1
kind: Service
metadata:
  name: {{ include "apo-dataplane.name" . }}-svc
  labels:
    {{- include "apo-dataplane.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
  selector:
    {{- include "apo-dataplane.labels" . | nindent 4 }}
  type: ClusterIP
